# Generated by Django 5.2.3 on 2025-06-17 13:48

import django.db.models.deletion
import task_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=task_manager.models.task_image_upload_path, verbose_name='Изображение')),
                ('position', models.CharField(choices=[('right_40', 'Справа 40% (обтекание текстом 60%)'), ('right_20', 'Справа 20% (обтекание текстом 80%)'), ('bottom_100', 'Снизу по центру 100% ширины'), ('bottom_70', 'Снизу по центру 70% ширины')], default='bottom_70', max_length=20, verbose_name='Расположение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к изображению')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task_manager.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Изображение задания',
                'verbose_name_plural': 'Изображения заданий',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
