# Generated by Django 5.2.3 on 2025-08-26 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_groups', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название работы')),
                ('duration', models.PositiveIntegerField(default=45, verbose_name='Время выполнения (минуты)')),
                ('variant_counter', models.PositiveIntegerField(default=0, verbose_name='Счётчик вариантов')),
                ('work_type', models.CharField(choices=[('test', 'Контрольная работа'), ('quiz', 'Самостоятельная работа'), ('exam', 'Экзамен'), ('diagnostic', 'Диагностическая работа'), ('homework', 'Домашняя работа'), ('practice', 'Практическая работа')], default='test', max_length=50, verbose_name='Тип работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.PositiveIntegerField(verbose_name='Номер варианта')),
                ('tasks', models.ManyToManyField(to='tasks.task', verbose_name='Задания')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['work', 'number'],
                'unique_together': {('work', 'number')},
            },
        ),
        migrations.CreateModel(
            name='WorkAnalogGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество заданий')),
                ('analog_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_groups.analoggroup', verbose_name='Группа аналогов')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Группа заданий в работе',
                'verbose_name_plural': 'Группы заданий в работе',
                'unique_together': {('work', 'analog_group')},
            },
        ),
    ]
