# Generated by Django 5.2.3 on 2026-03-02 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_varianttask_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttask',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Вес для нормировки баллов. По умолчанию = difficulty задачи', verbose_name='Вес задания'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер задания в варианте'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
