# Generated by Django 5.2.3 on 2026-03-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_varianttask_weight_alter_varianttask_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='max_score',
            field=models.PositiveIntegerField(default=100, help_text='Шкала для нормировки баллов', verbose_name='Максимальный балл'),
        ),
    ]
