# Generated by Django 5.2.3 on 2026-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttask',
            name='max_points',
            field=models.PositiveIntegerField(blank=True, help_text='Замороженные баллы по шкале. None = рассчитываются динамически.', null=True, verbose_name='Баллы (замороженные)'),
        ),
    ]
