# Generated by Django 5.2.3 on 2026-03-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_varianttask_max_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['number'], 'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variant',
            name='duration_snapshot',
            field=models.PositiveIntegerField(default=45, verbose_name='Время (снимок)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='max_score_snapshot',
            field=models.PositiveIntegerField(default=100, verbose_name='Макс. балл (снимок)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='work_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название работы (снимок)'),
        ),
        migrations.AddField(
            model_name='workanaloggroup',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Вес для нормировки баллов', verbose_name='Вес задания'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='max_points',
            field=models.PositiveIntegerField(default=0, help_text='Рассчитано при генерации из спецификации', verbose_name='Макс. баллов'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер задания'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес (deprecated)'),
        ),
        migrations.AlterField(
            model_name='workanaloggroup',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в работе'),
        ),
    ]
