# Generated by Django 5.2.3 on 2026-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_alter_variant_options_alter_variant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='max_score',
            field=models.PositiveIntegerField(default=0, help_text='Шкала нормировки. 0 = сумма весов (без нормировки)', verbose_name='Максимальный балл'),
        ),
    ]
