# Generated by Django 5.2.3 on 2026-03-07 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studenttasklog'),
        ('works', '0007_alter_work_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='assigned_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_variants', to='students.student', verbose_name='Назначен ученику'),
        ),
        migrations.AddField(
            model_name='variant',
            name='source_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remedial_variants', to='works.work', verbose_name='Работа-источник ошибок'),
        ),
        migrations.AddField(
            model_name='variant',
            name='variant_type',
            field=models.CharField(choices=[('regular', 'Обычный'), ('remedial', 'Работа над ошибками'), ('individual', 'Индивидуальный')], default='regular', max_length=20, verbose_name='Тип варианта'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('test', 'Контрольная работа'), ('quiz', 'Самостоятельная работа'), ('exam', 'Экзамен'), ('diagnostic', 'Диагностическая работа'), ('homework', 'Домашняя работа'), ('practice', 'Практическая работа'), ('remedial', 'Работа над ошибками'), ('individual', 'Индивидуальная работа')], default='test', max_length=50, verbose_name='Тип работы'),
        ),
    ]
