# Generated by Django 5.2.3 on 2026-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_variant_assigned_student_variant_source_work_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workanaloggroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='varianttask',
            name='bank_role',
            field=models.CharField(choices=[('demo', 'Демонстрационное'), ('practice', 'Для самостоятельной работы'), ('control', 'Контрольное'), ('remedial', 'Работа над ошибками')], default='control', max_length=20, verbose_name='Роль задания'),
        ),
        migrations.AddField(
            model_name='varianttask',
            name='blank_cells_after',
            field=models.BooleanField(default=False, verbose_name='Пустые клетки после задания'),
        ),
        migrations.AddField(
            model_name='varianttask',
            name='blank_cells_rows',
            field=models.PositiveIntegerField(default=6, verbose_name='Строк клеток'),
        ),
        migrations.AddField(
            model_name='varianttask',
            name='is_assessable',
            field=models.BooleanField(default=True, verbose_name='Оценивать'),
        ),
        migrations.AddField(
            model_name='varianttask',
            name='render_mode',
            field=models.CharField(choices=[('task_only', 'Только задание'), ('with_answer', 'Задание + ответ'), ('with_short_solution', 'Задание + краткое решение'), ('with_full_solution', 'Задание + полное решение')], default='task_only', max_length=40, verbose_name='Режим печати'),
        ),
        migrations.AddField(
            model_name='workanaloggroup',
            name='bank_role_filter',
            field=models.CharField(choices=[('any', 'Любая роль'), ('demo', 'Демонстрационное'), ('practice', 'Для самостоятельной работы'), ('control', 'Контрольное'), ('remedial', 'Работа над ошибками')], default='any', help_text='Какие задания выбирать из группы аналогов', max_length=20, verbose_name='Роль заданий'),
        ),
        migrations.AddField(
            model_name='workanaloggroup',
            name='blank_cells_after',
            field=models.BooleanField(default=False, verbose_name='Пустые клетки после задания'),
        ),
        migrations.AddField(
            model_name='workanaloggroup',
            name='blank_cells_rows',
            field=models.PositiveIntegerField(default=6, verbose_name='Строк клеток'),
        ),
        migrations.AddField(
            model_name='workanaloggroup',
            name='is_assessable',
            field=models.BooleanField(default=True, verbose_name='Оценивать'),
        ),
        migrations.AddField(
            model_name='workanaloggroup',
            name='render_mode',
            field=models.CharField(choices=[('task_only', 'Только задание'), ('with_answer', 'Задание + ответ'), ('with_short_solution', 'Задание + краткое решение'), ('with_full_solution', 'Задание + полное решение')], default='task_only', max_length=40, verbose_name='Режим печати'),
        ),
    ]
