# Generated by Django 5.2.3 on 2026-07-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_mark_task_scores'),
        ('works', '0009_alter_workanaloggroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='source_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_remedial_variants', to='events.eventparticipation', verbose_name='Исходная попытка ученика'),
        ),
    ]
