# Generated by Django 5.2.3 on 2026-07-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_variant_source_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttask',
            name='source_selection_id',
            field=models.CharField(blank=True, default='', help_text='Идентификатор блока спецификации на момент генерации; не является внешним ключом.', max_length=36, verbose_name='Исходный блок выбора заданий (снимок)'),
        ),
    ]
