# Generated by Django 5.2.3 on 2026-07-27 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_course_year_alter_course_academic_year'),
        ('works', '0011_varianttask_source_selection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('content_type', models.CharField(choices=[('theory', 'Теория'), ('text', 'Текст')], max_length=20, verbose_name='Тип содержимого')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в работе')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, help_text='Произвольный текст для текстового блока.', verbose_name='Текст')),
                ('include_subtopics', models.BooleanField(default=False, verbose_name='Включать подтемы')),
                ('topics', models.ManyToManyField(blank=True, help_text='Источники содержания для теоретического блока.', related_name='work_content_blocks', to='curriculum.topic', verbose_name='Темы')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Содержательный блок работы',
                'verbose_name_plural': 'Содержательные блоки работы',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
