# Generated by Django 5.2.3 on 2026-07-27 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_workcontentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttask',
            name='content_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок исходного блока (снимок)'),
        ),
        migrations.CreateModel(
            name='VariantContentBlockSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source_content_id', models.CharField(blank=True, default='', max_length=36, verbose_name='Исходный содержательный блок')),
                ('content_type', models.CharField(choices=[('theory', 'Теория'), ('text', 'Текст')], max_length=20, verbose_name='Тип содержимого')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в варианте')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (снимок)')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Содержимое (снимок)')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_block_snapshots', to='works.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Снимок содержательного блока варианта',
                'verbose_name_plural': 'Снимки содержательных блоков вариантов',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
