# Generated by Django 5.2.3 on 2026-08-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_difficulty'),
        ('works', '0013_varianttask_content_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttask',
            name='task_snapshot',
            field=models.JSONField(default=dict, help_text='Неизменяемое содержимое задания на момент генерации варианта.', verbose_name='Содержимое задания (снимок)'),
        ),
        migrations.AlterField(
            model_name='varianttask',
            name='task',
            field=models.ForeignKey(help_text='Связь с источником; печать использует сохранённый снимок.', on_delete=django.db.models.deletion.PROTECT, to='tasks.task', verbose_name='Исходное задание'),
        ),
    ]
