# Generated by Django 5.2.3 on 2026-08-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_attemptsnapshot_attempttasksnapshot_and_more'),
        ('works', '0014_varianttask_task_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='source_attempt_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_remedial_variants', to='events.attemptsnapshot', verbose_name='Снимок исходной проверенной попытки'),
        ),
    ]
