# Generated by Django 5.2.3 on 2026-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_variant_source_attempt_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='assessment_mode',
            field=models.CharField(choices=[('variant', 'По заданиям и вариантам'), ('aggregate', 'Итоговая оценка без варианта (внешний материал)')], default='variant', max_length=20, verbose_name='Режим оценивания'),
        ),
    ]
