# Generated by Django 5.2.3 on 2026-08-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_work_assessment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttask',
            name='page_break_after',
            field=models.BooleanField(default=False, verbose_name='Разрыв страницы после задания'),
        ),
        migrations.AddField(
            model_name='workanaloggroup',
            name='page_break_after',
            field=models.BooleanField(default=False, verbose_name='Разрыв страницы после задания'),
        ),
    ]
