# Generated by Django 5.2.3 on 2026-02-26 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('mode', models.CharField(choices=[('strict', 'Строгий'), ('update', 'Обновление'), ('skip', 'Пропуск дубликатов')], default='update', max_length=10, verbose_name='Режим')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Пробный запуск')),
                ('tasks_created', models.PositiveIntegerField(default=0, verbose_name='Заданий создано')),
                ('tasks_updated', models.PositiveIntegerField(default=0, verbose_name='Заданий обновлено')),
                ('tasks_skipped', models.PositiveIntegerField(default=0, verbose_name='Заданий пропущено')),
                ('groups_created', models.PositiveIntegerField(default=0, verbose_name='Групп создано')),
                ('topics_created', models.PositiveIntegerField(default=0, verbose_name='Тем создано')),
                ('images_created', models.PositiveIntegerField(default=0, verbose_name='Изображений создано')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Количество ошибок')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детальный отчёт')),
                ('error_messages', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('status', models.CharField(choices=[('validating', 'Валидация'), ('importing', 'Импорт'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='validating', max_length=20, verbose_name='Статус')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Длительность (мс)')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
