# Generated by Django 5.2.3 on 2026-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicyear'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_academic_year'),
        ),
    ]
