# Generated by Django 5.2.3 on 2026-08-02 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_alter_mark_task_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReportNarrativeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('possible_causes', models.TextField(blank=True, verbose_name='Возможные причины ошибок')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('planned_actions', models.TextField(blank=True, verbose_name='Запланированные мероприятия')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Дополнительные примечания')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report_narrative', to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Текст отчёта по событию',
                'verbose_name_plural': 'Тексты отчётов по событиям',
            },
        ),
    ]
