# Generated by Django 5.2.3 on 2026-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['-is_default', 'template_type', 'name'], 'verbose_name': 'Профиль печати', 'verbose_name_plural': 'Профили печати'},
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='default_content_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры секций по умолчанию'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Профиль печати по умолчанию'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='sections_config',
            field=models.JSONField(blank=True, default=list, help_text='JSON: [{"type": "header", "params": {...}}, ...]', verbose_name='Секции печати'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('work', 'Контрольная / самостоятельная'), ('remedial_sheet', 'Работа над ошибками'), ('worksheet', 'Рабочий лист'), ('answer_key', 'Ключ для проверки'), ('homework', 'Домашнее задание'), ('diagnostic', 'Диагностическая карта'), ('custom', 'Пользовательский')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
