# Generated by Django 5.2.3 on 2025-06-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название события')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('conducted', 'Проведено'), ('checked', 'Проверено'), ('graded', 'Оценено'), ('closed', 'Закрыто')], default='planned', max_length=20, verbose_name='Статус')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup', verbose_name='Класс')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Ученик')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'ordering': ['-created_at'],
            },
        ),
    ]
