# Generated by Django 5.2.3 on 2025-06-20 10:25

import django.db.models.deletion
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
        ('students', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название события')),
                ('planned_date', models.DateTimeField(verbose_name='Запланированная дата')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'Выполняется'), ('completed', 'Завершено'), ('reviewing', 'На проверке'), ('graded', 'Проверено'), ('closed', 'Закрыто')], default='planned', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание события')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Место проведения')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.course', verbose_name='Курс')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('started', 'Начал выполнение'), ('completed', 'Завершил'), ('graded', 'Проверено'), ('absent', 'Отсутствовал')], default='assigned', max_length=20, verbose_name='Статус участия')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начал в')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершил в')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено в')),
                ('seat_number', models.CharField(blank=True, max_length=20, verbose_name='Место')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Ученик')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.variant', verbose_name='Назначенный вариант')),
            ],
            options={
                'verbose_name': 'Участие в событии',
                'verbose_name_plural': 'Участие в событиях',
                'ordering': ['event', 'student'],
                'unique_together': {('event', 'student')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(through='events.EventParticipation', to='students.student', verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, verbose_name='Оценка')),
                ('points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Набранные баллы')),
                ('max_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум баллов')),
                ('work_scan', models.FileField(blank=True, help_text='PDF скан выполненной работы', null=True, upload_to=events.models.work_scan_upload_path, verbose_name='Скан работы')),
                ('task_scores', models.JSONField(blank=True, default=dict, help_text='{"task_id": {"points": 2, "max_points": 3, "comment": "..."}}', verbose_name='Баллы по заданиям')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('mistakes_analysis', models.TextField(blank=True, verbose_name='Анализ ошибок')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено в')),
                ('checked_by', models.CharField(blank=True, max_length=100, verbose_name='Проверил')),
                ('is_retake', models.BooleanField(default=False, verbose_name='Пересдача')),
                ('is_excellent', models.BooleanField(default=False, verbose_name='Отличная работа')),
                ('needs_attention', models.BooleanField(default=False, verbose_name='Требует внимания')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.eventparticipation', verbose_name='Участие в событии')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'ordering': ['-created_at'],
            },
        ),
    ]
