# Generated by Django 5.2.3 on 2026-03-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('works', '0007_alter_work_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='works.variant', verbose_name='Назначенный вариант'),
        ),
    ]
