# Generated by Django 5.2.3 on 2026-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventparticipation_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='task_scores',
            field=models.JSONField(blank=True, default=dict, help_text='{"variant_task_id": {"task_id": "...", "points": 2, "max_points": 3, "comment": "..."}}', verbose_name='Баллы по заданиям'),
        ),
    ]
