# Generated by Django 5.2.3 on 2026-08-02 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_mark_task_scores'),
        ('works', '0014_varianttask_task_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('revision', models.PositiveIntegerField(verbose_name='Ревизия')),
                ('student_id_snapshot', models.CharField(max_length=36, verbose_name='ID ученика (снимок)')),
                ('student_name_snapshot', models.CharField(max_length=300, verbose_name='Ученик (снимок)')),
                ('event_id_snapshot', models.CharField(max_length=36, verbose_name='ID события (снимок)')),
                ('event_name_snapshot', models.CharField(max_length=200, verbose_name='Событие (снимок)')),
                ('event_date_snapshot', models.DateTimeField(verbose_name='Дата события (снимок)')),
                ('work_id_snapshot', models.CharField(max_length=36, verbose_name='ID работы (снимок)')),
                ('work_name_snapshot', models.CharField(max_length=200, verbose_name='Работа (снимок)')),
                ('variant_id_snapshot', models.CharField(blank=True, max_length=36, verbose_name='ID варианта (снимок)')),
                ('variant_number_snapshot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер варианта (снимок)')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Набранные баллы')),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Максимум баллов')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('mistakes_analysis', models.TextField(blank=True, verbose_name='Анализ ошибок')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('checked_at_snapshot', models.DateTimeField(blank=True, null=True, verbose_name='Проверено в (снимок)')),
                ('checked_by_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Проверил (снимок)')),
                ('is_retake', models.BooleanField(default=False, verbose_name='Пересдача')),
                ('is_excellent', models.BooleanField(default=False, verbose_name='Отличная работа')),
                ('needs_attention', models.BooleanField(default=False, verbose_name='Требует внимания')),
                ('task_scores_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Баллы по заданиям (снимок)')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_snapshots', to='events.mark', verbose_name='Проверка-источник')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_snapshots', to='events.eventparticipation', verbose_name='Участие')),
            ],
            options={
                'verbose_name': 'Снимок проверенной попытки',
                'verbose_name_plural': 'Снимки проверенных попыток',
                'ordering': ['participation_id', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='AttemptTaskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('task_id_snapshot', models.CharField(max_length=36, verbose_name='ID задания (снимок)')),
                ('order_snapshot', models.PositiveIntegerField(verbose_name='Номер задания (снимок)')),
                ('is_assessable_snapshot', models.BooleanField(verbose_name='Оценивалось (снимок)')),
                ('expected_max_points_snapshot', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Максимум по варианту (снимок)')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Набранные баллы')),
                ('checked_max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Максимум при проверке')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='events.attemptsnapshot', verbose_name='Снимок попытки')),
                ('variant_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_task_snapshots', to='works.varianttask', verbose_name='Задание варианта')),
            ],
            options={
                'verbose_name': 'Результат задания в снимке попытки',
                'verbose_name_plural': 'Результаты заданий в снимках попыток',
                'ordering': ['order_snapshot', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='attemptsnapshot',
            constraint=models.UniqueConstraint(fields=('participation', 'revision'), name='unique_attempt_snapshot_revision'),
        ),
        migrations.AddConstraint(
            model_name='attempttasksnapshot',
            constraint=models.UniqueConstraint(fields=('attempt', 'variant_task'), name='unique_attempt_snapshot_variant_task'),
        ),
    ]
