# Generated by Django 5.2.3 on 2026-08-08 08:27

from django.db import migrations, models


def backfill_task_slot_metadata(apps, schema_editor):
    AttemptTaskSnapshot = apps.get_model('events', 'AttemptTaskSnapshot')
    rows = list(
        AttemptTaskSnapshot.objects.using(
            schema_editor.connection.alias,
        ).select_related('variant_task')
    )
    for row in rows:
        row.source_selection_id_snapshot = (
            row.variant_task.source_selection_id
        )
        row.content_order_snapshot = row.variant_task.content_order
    if rows:
        AttemptTaskSnapshot.objects.using(
            schema_editor.connection.alias,
        ).bulk_update(
            rows,
            ['source_selection_id_snapshot', 'content_order_snapshot'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_attemptsnapshot_attempttasksnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttasksnapshot',
            name='content_order_snapshot',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок блока спецификации (снимок)'),
        ),
        migrations.AddField(
            model_name='attempttasksnapshot',
            name='source_selection_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Блок спецификации (снимок)'),
        ),
        migrations.RunPython(
            backfill_task_slot_metadata,
            migrations.RunPython.noop,
        ),
    ]
