# Generated by Django 5.2.3 on 2026-08-08 09:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_task_content_snapshots(apps, schema_editor):
    AttemptTaskSnapshot = apps.get_model('events', 'AttemptTaskSnapshot')
    rows = list(
        AttemptTaskSnapshot.objects.using(
            schema_editor.connection.alias,
        ).select_related('variant_task')
    )
    for row in rows:
        row.task_content_snapshot = dict(
            row.variant_task.task_snapshot or {},
        )
    if rows:
        AttemptTaskSnapshot.objects.using(
            schema_editor.connection.alias,
        ).bulk_update(rows, ['task_content_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_attempttasksnapshot_content_order_snapshot_and_more'),
        ('works', '0015_variant_source_attempt_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttasksnapshot',
            name='task_content_snapshot',
            field=models.JSONField(default=dict, verbose_name='Содержимое задания (снимок)'),
        ),
        migrations.RunPython(
            backfill_task_content_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='attempttasksnapshot',
            name='variant_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_task_snapshots', to='works.varianttask', verbose_name='Задание варианта'),
        ),
        migrations.AddConstraint(
            model_name='attempttasksnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('variant_task__isnull', True)), fields=('attempt', 'task_id_snapshot'), name='unique_attempt_snapshot_legacy_task'),
        ),
    ]
