# Generated by Django 5.2.3 on 2026-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_attempttasksnapshot_task_content_snapshot_and_more'),
        ('works', '0016_work_assessment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptsnapshot',
            name='work_assessment_mode_snapshot',
            field=models.CharField(choices=[('variant', 'По заданиям и вариантам'), ('aggregate', 'Итоговая оценка без варианта (внешний материал)')], default='variant', max_length=20, verbose_name='Режим оценивания работы (снимок)'),
        ),
    ]
