# Generated by Django 5.2.3 on 2025-06-19 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('category', models.CharField(choices=[('excellent', 'Отличная работа'), ('good', 'Хорошая работа'), ('needs_improvement', 'Требует улучшения'), ('mistake', 'Типичная ошибка'), ('suggestion', 'Рекомендация')], max_length=50, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Типовой комментарий',
                'verbose_name_plural': 'Типовые комментарии',
                'ordering': ['-usage_count', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало проверки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание проверки')),
                ('total_participations', models.PositiveIntegerField(default=0, verbose_name='Всего работ')),
                ('checked_participations', models.PositiveIntegerField(default=0, verbose_name='Проверено работ')),
                ('average_time_per_work', models.DurationField(blank=True, null=True, verbose_name='Среднее время на работу')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
            ],
            options={
                'verbose_name': 'Сессия проверки',
                'verbose_name_plural': 'Сессии проверки',
            },
        ),
    ]
