# Generated by Django 5.2.3 on 2026-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analoggroup',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Начальный'), (2, 'Базовый'), (3, 'Базовый+'), (4, 'Повышенный'), (5, 'Высокий'), (6, 'Олимпиадный')], default=0, help_text='0 = авто-определение из медианы заданий', verbose_name='Номинальная сложность'),
        ),
    ]
