# Generated by Django 5.2.3 on 2026-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_groups', '0002_analoggroup_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='bank_role',
            field=models.CharField(choices=[('demo', 'Демонстрационное'), ('practice', 'Для самостоятельной работы'), ('control', 'Контрольное'), ('remedial', 'Работа над ошибками')], db_index=True, default='control', max_length=20, verbose_name='Роль задания в банке'),
        ),
    ]
