# Generated by Django 5.2.3 on 2025-06-20 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.CharField(choices=[('task_types', 'Типы заданий'), ('difficulty_levels', 'Уровни сложности'), ('cognitive_levels', 'Когнитивные уровни'), ('work_types', 'Типы работ'), ('subjects', 'Предметы'), ('comment_categories', 'Категории комментариев')], help_text='Тип справочника', max_length=50, unique=True, verbose_name='Категория')),
                ('items_text', models.TextField(blank=True, help_text='Каждый элемент с новой строки.\nПример:\nРасчётная задача\nКачественная задача\nТеоретический вопрос', verbose_name='Элементы справочника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='SubjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('subject', models.CharField(help_text='Предмет из справочника предметов', max_length=100, verbose_name='Предмет')),
                ('grade_level', models.CharField(blank=True, help_text='Класс (например: 5, 7-9, 10-11). Если пусто - для всех классов', max_length=50, verbose_name='Класс')),
                ('category', models.CharField(choices=[('content_elements', 'Элементы содержания'), ('requirement_elements', 'Элементы требований')], max_length=50, verbose_name='Категория')),
                ('items_text', models.TextField(blank=True, help_text='Формат: код|название (каждый с новой строки)\nПример:\n1.1|Натуральные числа\n1.2|Дроби\nИли просто:\nНатуральные числа\nДроби', verbose_name='Элементы кодификатора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Справочник кодификатора',
                'verbose_name_plural': 'Справочники кодификатора',
                'ordering': ['subject', 'grade_level', 'category'],
                'unique_together': {('subject', 'grade_level', 'category')},
            },
        ),
    ]
