# Generated by Django 5.2.3 on 2025-06-19 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(help_text='Уникальный код для программного доступа', max_length=50, unique=True, verbose_name='Код категории')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, help_text='Системные категории нельзя удалять', verbose_name='Системная категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория справочника',
                'verbose_name_plural': 'Категории справочников',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(help_text='Уникальный код в рамках категории', max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('numeric_value', models.IntegerField(blank=True, help_text='Для уровней сложности, классов и т.п.', null=True, verbose_name='Числовое значение')),
                ('color', models.CharField(blank=True, help_text='HEX код цвета для отображения (#FF0000)', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, help_text='CSS класс иконки (например: fas fa-star)', max_length=50, verbose_name='Иконка')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='JSON с дополнительными параметрами', verbose_name='Дополнительные данные')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='references.referencecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочников',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
