# Generated by Django 5.2.3 on 2025-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectreference',
            options={'ordering': ['subject', 'grade_level', 'category'], 'verbose_name': 'Справочник кодификатора', 'verbose_name_plural': 'Справочники кодификатора'},
        ),
        migrations.AlterUniqueTogether(
            name='subjectreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectreference',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Класс (например: 5, 7-9, 10-11). Если пусто - для всех классов', max_length=50, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='subjectreference',
            name='subject',
            field=models.CharField(help_text='Предмет из справочника предметов', max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectreference',
            unique_together={('subject', 'grade_level', 'category')},
        ),
    ]
