# Generated by Django 5.2.3 on 2025-06-20 10:25

import django.db.models.deletion
import tasks.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('short_solution', models.TextField(blank=True, verbose_name='Краткое решение')),
                ('full_solution', models.TextField(blank=True, verbose_name='Полное решение')),
                ('hint', models.TextField(blank=True, verbose_name='Подсказка')),
                ('instruction', models.TextField(blank=True, verbose_name='Инструкция к выполнению')),
                ('content_element', models.CharField(blank=True, max_length=100, verbose_name='Элемент содержания')),
                ('requirement_element', models.CharField(blank=True, max_length=100, verbose_name='Элемент требований')),
                ('task_type', models.CharField(choices=[('qualitative', 'Качественная задача'), ('computational', 'Расчётная задача'), ('theoretical', 'Теоретический вопрос'), ('practical', 'Практическое задание'), ('test', 'Тестовое задание')], max_length=20, verbose_name='Тип задания')),
                ('difficulty', models.IntegerField(choices=[(1, 'Подготовительный'), (2, 'Базовый'), (3, 'Повышенный'), (4, 'Высокий'), (5, 'Экспертный')], verbose_name='Сложность')),
                ('cognitive_level', models.CharField(choices=[('remember', 'Запоминание'), ('understand', 'Понимание'), ('apply', 'Применение'), ('analyze', 'Анализ'), ('evaluate', 'Оценка'), ('create', 'Создание')], default='understand', max_length=20, verbose_name='Уровень познания')),
                ('estimated_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время выполнения (мин)')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subtopic', verbose_name='Подтема')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.topic', verbose_name='Основная тема')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to=tasks.models.task_image_upload_path, verbose_name='Изображение')),
                ('position', models.CharField(choices=[('right_40', 'Справа 40% (обтекание текстом 60%)'), ('right_20', 'Справа 20% (обтекание текстом 80%)'), ('bottom_100', 'Снизу по центру 100% ширины'), ('bottom_70', 'Снизу по центру 70% ширины')], default='bottom_70', max_length=20, verbose_name='Расположение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к изображению')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок отображения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Изображение задания',
                'verbose_name_plural': 'Изображения заданий',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
