# Generated by Django 5.2.3 on 2025-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='position',
            field=models.CharField(blank=True, choices=[('right_40', 'Справа 40% (обтекание текстом 60%)'), ('right_20', 'Справа 20% (обтекание текстом 80%)'), ('bottom_100', 'Снизу по центру 100% ширины'), ('bottom_70', 'Снизу по центру 70% ширины')], help_text='Оставьте пустым для установки позже', max_length=20, verbose_name='Расположение'),
        ),
    ]
