# Generated by Django 5.2.3 on 2025-06-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Подготовительный'), (2, 'Базовый'), (3, 'Повышенный'), (4, 'Высокий'), (5, 'Экспертный')], help_text='Уровень сложности задания', verbose_name='Сложность'),
        ),
    ]
