# Generated by Django 5.2.3 on 2026-03-06 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_allow_empty_image_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Например: Перышкин А.В. Физика. 8 класс', max_length=300, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, help_text='Например: Перышкин-8', max_length=100, verbose_name='Краткое название')),
                ('source_type', models.CharField(choices=[('textbook', 'Учебник'), ('problem_book', 'Задачник'), ('exam', 'ЕГЭ/ОГЭ'), ('olympiad', 'Олимпиада'), ('website', 'Сайт'), ('original', 'Авторское'), ('other', 'Другое')], default='textbook', max_length=50, verbose_name='Тип источника')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('url', models.URLField(blank=True, help_text='URL сайта или онлайн-ресурса', verbose_name='Ссылка')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.PositiveIntegerField(blank=True, choices=[(7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], help_text='Рекомендуемый класс (7–11)', null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Задание вычитано, ответ проверен', verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_detail',
            field=models.CharField(blank=True, help_text='Стр. 45, №12 / Вариант 3, задание 5', max_length=200, verbose_name='Детали источника'),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher_notes',
            field=models.TextField(blank=True, help_text='Личные пометки: особенности, типичные ошибки учеников', verbose_name='Заметки учителя'),
        ),
        migrations.AddField(
            model_name='task',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Год составления/публикации (ЕГЭ 2024, олимпиада 2023)', null=True, verbose_name='Год задания'),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Книга, сайт, сборник, откуда взято задание', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.source', verbose_name='Источник'),
        ),
    ]
