# Generated by Django 5.2.3 on 2026-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_shift_difficulty_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Начальный'), (2, 'Базовый'), (3, 'Базовый+'), (4, 'Повышенный'), (5, 'Высокий'), (6, 'Олимпиадный')], help_text='Уровень сложности задания', verbose_name='Сложность'),
        ),
    ]
