# Generated by Django 5.2.3 on 2026-08-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content_element',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requirement_element',
        ),
    ]
