# Generated by Django 5.2.3 on 2026-08-22 08:00

import django.db.models.deletion
import hashlib
import mimetypes
import tasks.models
import uuid
from django.db import migrations, models


def backfill_image_assets(apps, schema_editor):
    ImageAsset = apps.get_model('tasks', 'ImageAsset')
    TaskImage = apps.get_model('tasks', 'TaskImage')

    for task_image in TaskImage.objects.exclude(image='').iterator():
        image_file = task_image.image
        try:
            digest = hashlib.sha256()
            byte_size = 0
            with image_file.open('rb') as opened_file:
                for chunk in iter(lambda: opened_file.read(64 * 1024), b''):
                    digest.update(chunk)
                    byte_size += len(chunk)
        except (OSError, ValueError):
            continue

        checksum = digest.hexdigest()
        asset, _ = ImageAsset.objects.get_or_create(
            checksum=checksum,
            defaults={
                'file': image_file.name,
                'byte_size': byte_size,
                'mime_type': (
                    mimetypes.guess_type(image_file.name)[0]
                    or 'application/octet-stream'
                ),
                'original_filename': image_file.name.rsplit('/', 1)[-1],
            },
        )
        task_image.asset_id = asset.pk
        task_image.save(update_fields=['asset'])


def restore_task_image_paths(apps, schema_editor):
    TaskImage = apps.get_model('tasks', 'TaskImage')
    for task_image in TaskImage.objects.select_related('asset').iterator():
        if task_image.asset_id:
            task_image.image = task_image.asset.file.name
            task_image.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_content_element_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file', models.FileField(upload_to=tasks.models.image_asset_upload_path, verbose_name='Файл')),
                ('checksum', models.CharField(editable=False, max_length=64, unique=True, verbose_name='SHA-256')),
                ('byte_size', models.PositiveBigIntegerField(editable=False, verbose_name='Размер, байт')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='MIME-тип')),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Исходное имя файла')),
            ],
            options={
                'verbose_name': 'Неизменяемый файл изображения',
                'verbose_name_plural': 'Неизменяемые файлы изображений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskimage',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Пусто только у старых записей с потерянным файлом', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_references', to='tasks.imageasset', verbose_name='Файл изображения'),
        ),
        migrations.RunPython(
            backfill_image_assets,
            restore_task_image_paths,
        ),
        migrations.RemoveField(
            model_name='taskimage',
            name='image',
        ),
    ]
