# Generated by Django 5.2.3 on 2026-02-27 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_add_course_student_groups'),
        ('tasks', '0002_allow_empty_image_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodifierSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Полное название')),
                ('short_name', models.CharField(help_text='Например: ОГЭ 2026', max_length=30, verbose_name='Краткое название')),
                ('subject', models.CharField(default='Физика', max_length=100, verbose_name='Предмет')),
                ('exam_type', models.CharField(choices=[('oge', 'ОГЭ'), ('ege', 'ЕГЭ'), ('vpr', 'ВПР'), ('custom', 'Авторский')], max_length=20, verbose_name='Тип экзамена')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Кодификатор',
                'verbose_name_plural': 'Кодификаторы',
                'ordering': ['-year', 'exam_type'],
                'unique_together': {('exam_type', 'year', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(help_text='Например: 1.4, 1.1.6, 3.2.3', max_length=20, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Формулировка')),
                ('grade_studied', models.CharField(blank=True, help_text='7, 8, 9 или 7, 9', max_length=20, verbose_name='Класс изучения')),
                ('codifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_entries', to='codifier.codifierspec', verbose_name='Кодификатор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='codifier.contententry', verbose_name='Родительский элемент')),
                ('topic', models.ForeignKey(blank=True, help_text='Привязка к теме из учебного плана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codifier_entries', to='curriculum.topic', verbose_name='Тема (curriculum)')),
            ],
            options={
                'verbose_name': 'Элемент содержания',
                'verbose_name_plural': 'Элементы содержания',
                'ordering': ['codifier', 'code'],
                'unique_together': {('codifier', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('name', models.TextField(verbose_name='Формулировка')),
                ('cognitive_level', models.CharField(blank=True, choices=[('know', 'Знать / понимать'), ('apply', 'Уметь'), ('use', 'Использовать на практике')], max_length=20, verbose_name='Когнитивный уровень')),
                ('codifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='codifier.codifierspec', verbose_name='Кодификатор')),
                ('tasks', models.ManyToManyField(blank=True, related_name='codifier_requirements', to='tasks.task', verbose_name='Задания')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
                'ordering': ['codifier', 'code'],
                'unique_together': {('codifier', 'code')},
            },
        ),
    ]
