# Generated by Django 5.2.3 on 2026-02-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifier', '0001_initial'),
        ('curriculum', '0003_add_course_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='subtopic',
            field=models.ForeignKey(blank=True, help_text='Конкретный элемент (Равноускоренное движение...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codifier_entries', to='curriculum.subtopic', verbose_name='Подтема'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Общая тема (Кинематика, Динамика...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codifier_entries', to='curriculum.topic', verbose_name='Тема'),
        ),
    ]
