"""Document and section type identifiers."""


WORK_DOCUMENT_TYPE = 'work'
REMEDIAL_SHEET_DOCUMENT_TYPE = 'remedial_sheet'
WORKSHEET_DOCUMENT_TYPE = 'worksheet'
ANSWER_KEY_DOCUMENT_TYPE = 'answer_key'
HOMEWORK_DOCUMENT_TYPE = 'homework'
DIAGNOSTIC_DOCUMENT_TYPE = 'diagnostic'
CUSTOM_DOCUMENT_TYPE = 'custom'
EVENT_PERFORMANCE_REPORT_DOCUMENT_TYPE = 'event_performance_report'
STUDENT_DIGEST_DOCUMENT_TYPE = 'student_digest'

HEADER_SECTION = 'header'
COMMON_HEADER_SECTION = 'common_header'
TASK_LIST_SECTION = 'task_list'
ANSWER_KEY_SECTION = 'answer_key'
ANSWERS_SECTION = 'answers'
SHORT_SOLUTIONS_SECTION = 'short_solutions'
FULL_SOLUTIONS_SECTION = 'full_solutions'
ORIGINAL_MISTAKES_SECTION = 'original_mistakes'
TRAINING_TASKS_SECTION = 'training_tasks'
PAGE_BREAK_SECTION = 'page_break'
SCORE_TABLE_SECTION = 'score_table'
BLANK_CELLS_SECTION = 'blank_cells'
EVENT_REPORT_SUMMARY_SECTION = 'event_report_summary'
EVENT_REPORT_SPECIFICATION_SECTION = 'event_report_specification'
EVENT_REPORT_TASK_ANALYSIS_SECTION = 'event_report_task_analysis'
EVENT_REPORT_CONCLUSIONS_SECTION = 'event_report_conclusions'
STUDENT_DIGEST_SUMMARY_SECTION = 'student_digest_summary'
STUDENT_DIGEST_RETAKES_SECTION = 'student_digest_retakes'
STUDENT_DIGEST_DETAILS_SECTION = 'student_digest_details'
STUDENT_DIGEST_FOCUS_SECTION = 'student_digest_focus'
