# Generated by Django 5.2.3 on 2025-07-20 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название подтемы')),
                ('description', models.TextField(blank=True, verbose_name='Описание подтемы')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок в теме')),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Подтемы',
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название темы')),
                ('subject', models.CharField(help_text='Предмет из справочника предметов', max_length=100, verbose_name='Предмет')),
                ('section', models.CharField(max_length=200, verbose_name='Тематический раздел')),
                ('grade_level', models.PositiveIntegerField(help_text='7, 8, 9, 10, 11', verbose_name='Класс')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок изучения')),
                ('description', models.TextField(blank=True, verbose_name='Описание темы')),
                ('difficulty_level', models.PositiveIntegerField(choices=[(1, 'Базовый'), (2, 'Повышенный'), (3, 'Углубленный')], default=1, verbose_name='Базовый уровень сложности')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['subject', 'grade_level', 'section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание курса')),
                ('subject', models.CharField(help_text='Предмет из справочника предметов', max_length=100, verbose_name='Предмет')),
                ('grade_level', models.PositiveIntegerField(verbose_name='Класс')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20, verbose_name='Учебный год')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее количество часов')),
                ('hours_per_week', models.PositiveIntegerField(default=2, verbose_name='Часов в неделю')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['grade_level', 'subject', 'name'],
                'unique_together': {('name', 'subject', 'grade_level', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок в курсе')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Запланированная дата')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес в итоговой оценке')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Работа в курсе',
                'verbose_name_plural': 'Работы в курсах',
                'ordering': ['course', 'order'],
            },
        ),
    ]
