# Generated by Django 5.2.3 on 2025-06-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работа'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'subject', 'grade_level', 'section')},
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='curriculum.topic', verbose_name='Основная тема'),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'work')},
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'name')},
        ),
    ]
