# Generated by Django 5.2.3 on 2025-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(help_text='Предмет из справочника предметов', max_length=100, verbose_name='Предмет'),
        ),
    ]
