# Generated by Django 5.2.3 on 2026-02-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_groups',
            field=models.ManyToManyField(blank=True, help_text='Классы, которым назначен этот курс', related_name='courses', to='students.studentgroup', verbose_name='Классы'),
        ),
    ]
