# Generated by Django 5.2.3 on 2026-02-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicyear'),
        ('curriculum', '0003_add_course_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=20, verbose_name='Учебный год (старое)'),
        ),
    ]
