# Generated by Django 5.2.3 on 2026-08-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicyear'),
        ('curriculum', '0004_course_year_alter_course_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'subject', 'grade_level', 'year')},
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.academicyear', verbose_name='Учебный год'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
    ]
