"""Named Django test label groups for focused development runs."""

TEST_SLICES = {
    'clean': (
        'core_logic.tests',
    ),
    'reports': (
        'core_logic.tests.test_event_performance_report',
        'core_logic.tests.test_get_events_status_report',
        'core_logic.tests.test_get_heatmap_course_overview',
        'core_logic.tests.test_get_heatmap_course_timeline',
        'core_logic.tests.test_get_heatmap_course_topic_matrix',
        'core_logic.tests.test_get_heatmap_drilldown_overview',
        'core_logic.tests.test_get_heatmap_overview',
        'core_logic.tests.test_get_heatmap_student_detail',
        'core_logic.tests.test_get_heatmap_subtopic_detail',
        'core_logic.tests.test_get_heatmap_subtopic_matrix',
        'core_logic.tests.test_get_heatmap_topic_matrix',
        'core_logic.tests.test_get_journal',
        'core_logic.tests.test_get_journal_select',
        'core_logic.tests.test_get_reports_dashboard',
        'core_logic.tests.test_get_student_performance_report',
        'core_logic.tests.test_get_work_analysis_report',
        'core_logic.tests.test_report_document_recipes',
        'core_logic.tests.test_report_services',
        'core_logic.tests.test_student_digests',
        'infrastructure.tests.test_attempt_snapshots',
        'infrastructure.tests.test_django_attempt_snapshot_queries',
        'infrastructure.tests.test_django_captured_task_result_queries',
        'infrastructure.tests.test_django_report_repo',
        'infrastructure.tests.test_django_journal_repo',
        'infrastructure.tests.test_django_task_db_health_repo',
        'infrastructure.tests.test_report_document_payloads',
        'infrastructure.tests.test_written_reports',
        'reports.tests',
    ),
    'documents': (
        'core_logic.tests.test_document',
        'core_logic.tests.test_document_builder_service',
        'core_logic.tests.test_document_recipe_factories',
        'core_logic.tests.test_document_render_options',
        'core_logic.tests.test_document_render_plan',
        'core_logic.tests.test_document_render_recipe_factories',
        'core_logic.tests.test_document_render_requests',
        'core_logic.tests.test_document_renderer_registry',
        'core_logic.tests.test_document_rendering_interfaces',
        'core_logic.tests.test_document_rendering_use_cases',
        'core_logic.tests.test_document_section_catalog',
        'core_logic.tests.test_document_type_catalog',
        'core_logic.tests.test_render_document_from_recipe',
        'core_logic.tests.test_sectioned_document_renderer',
        'core_logic.tests.test_variant_print_plan',
        'document_engine.tests',
        'infrastructure.tests.test_django_document_section_payloads',
        'infrastructure.tests.test_document_container_integration',
        'infrastructure.tests.test_latex_document_payloads',
        'infrastructure.tests.test_report_document_payloads',
        'infrastructure.tests.test_rendered_document_file_store',
        'infrastructure.tests.test_sectioned_document_defaults',
        'infrastructure.tests.test_sectioned_document_file_renderer',
        'infrastructure.tests.test_sectioned_document_html_templates',
        'infrastructure.tests.test_sectioned_document_latex_templates',
        'infrastructure.tests.test_sectioned_document_renderer_factory',
        'infrastructure.tests.test_sectioned_document_renderer_specs',
        'infrastructure.tests.test_task_document_payloads',
        'infrastructure.tests.test_task_image_presentation',
        'infrastructure.tests.test_template_document_content_wrapper',
        'infrastructure.tests.test_template_document_section_renderer',
        'infrastructure.tests.test_template_section_renderer_registry_factory',
    ),
    'works': (
        'works.tests',
        'core_logic.tests.test_create_work_from_groups',
        'core_logic.tests.test_create_work_from_tasks',
        'core_logic.tests.test_save_work',
        'core_logic.tests.test_variant_display',
        'core_logic.tests.test_work_content_plan',
        'core_logic.tests.test_work_detail',
        'core_logic.tests.test_work_score_allocation_service',
        'core_logic.tests.test_work_spec_sync_service',
        'core_logic.tests.test_work_specification',
        'core_logic.tests.test_work_variant_composition_service',
    ),
    'students': (
        'students.tests',
        'core_logic.tests.test_get_student_detail',
        'core_logic.tests.test_get_student_lists',
        'core_logic.tests.test_get_student_profile',
        'core_logic.tests.test_save_student',
        'core_logic.tests.test_student_task_result_service',
    ),
    'tasks': (
        'tasks.tests',
        'task_groups.tests',
        'codifier.tests',
        'curriculum.tests',
        'core_logic.tests.test_codifier_service',
        'core_logic.tests.test_execute_task_import',
        'core_logic.tests.test_export_tasks',
        'core_logic.tests.test_save_task',
        'core_logic.tests.test_task_content_snapshot',
        'core_logic.tests.test_task_group_membership',
        'core_logic.tests.test_task_scores',
        'core_logic.tests.test_task_validation',
    ),
    'events': (
        'events.tests',
        'review.tests',
        'core_logic.tests.test_create_remedial_from_event',
        'core_logic.tests.test_event_list_and_detail',
        'core_logic.tests.test_event_mutations',
        'core_logic.tests.test_get_remedial_event_preview',
        'core_logic.tests.test_grade_student_work',
        'core_logic.tests.test_grading_service',
        'core_logic.tests.test_remedial_service',
        'core_logic.tests.test_review_actions',
        'core_logic.tests.test_review_service',
        'infrastructure.tests.test_attempt_snapshots',
        'infrastructure.tests.test_django_event_attempt_queries',
    ),
    'infrastructure': (
        'infrastructure.tests',
    ),
    'web': (
        'codifier.tests',
        'core.tests',
        'curriculum.tests',
        'document_engine.tests.test_views',
        'events.tests',
        'reports.tests',
        'review.tests',
        'site_settings.tests',
        'students.tests',
        'task_groups.tests',
        'tasks.tests',
        'works.tests',
    ),
    'all': (),
}


def get_test_slice(name):
    """Return labels for a named slice or raise KeyError for unknown names."""
    return TEST_SLICES[name]
