# Generated by Django 5.2.3 on 2026-02-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicyear'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='core.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('name', 'academic_year')},
        ),
    ]
