# Generated by Django 5.2.3 on 2026-03-07 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_course_year_alter_course_academic_year'),
        ('events', '0002_alter_eventparticipation_variant'),
        ('students', '0002_studentgroup_academic_year_and_more'),
        ('task_groups', '0001_initial'),
        ('tasks', '0003_source_task_grade_task_is_verified_and_more'),
        ('works', '0007_alter_work_max_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name='Сложность (кэш)')),
                ('points', models.FloatField(blank=True, null=True, verbose_name='Набранные баллы')),
                ('max_points', models.FloatField(blank=True, null=True, verbose_name='Макс. баллы')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Выполнено верно')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Процент выполнения')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('completed_at', models.DateTimeField(verbose_name='Дата выполнения')),
                ('analog_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_groups.analoggroup', verbose_name='Группа аналогов (кэш)')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event', verbose_name='Событие')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.mark', verbose_name='Отметка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_log', to='students.student', verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_log', to='tasks.task', verbose_name='Задание')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.topic', verbose_name='Тема (кэш)')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student', 'task'], name='students_st_student_5bf137_idx'), models.Index(fields=['student', 'topic'], name='students_st_student_1333ff_idx'), models.Index(fields=['student', 'analog_group'], name='students_st_student_344f5e_idx'), models.Index(fields=['student', 'completed_at'], name='students_st_student_40cad2_idx'), models.Index(fields=['task', 'is_correct'], name='students_st_task_id_b9398c_idx'), models.Index(fields=['student', 'is_correct'], name='students_st_student_db6b58_idx')],
            },
        ),
    ]
