# Generated by Django 5.2.3 on 2026-07-30 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_course_year_alter_course_academic_year'),
        ('events', '0003_alter_mark_task_scores'),
        ('students', '0004_studenttasklog_variant_task'),
        ('task_groups', '0003_taskgroup_bank_role'),
        ('tasks', '0005_alter_task_difficulty'),
        ('works', '0013_varianttask_content_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttasklog',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subtopic', verbose_name='Подтема (кэш)'),
        ),
        migrations.AddIndex(
            model_name='studenttasklog',
            index=models.Index(fields=['student', 'subtopic'], name='students_st_student_6b4377_idx'),
        ),
    ]
