# Generated by Django 5.2.3 on 2026-08-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studenttasklog_subtopic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTaskLog',
        ),
    ]
