# Generated by Django 5.2.3 on 2026-03-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, default='', help_text='Для шапки документов', max_length=200, verbose_name='Название школы')),
                ('teacher_name', models.CharField(blank=True, default='', help_text='Для шапки документов', max_length=200, verbose_name='ФИО учителя')),
                ('default_subject', models.CharField(blank=True, default='Физика', help_text='Используется при импорте и создании', max_length=100, verbose_name='Предмет по умолчанию')),
                ('points_scale', models.IntegerField(default=100, help_text='Макс. балл за работу по умолчанию', verbose_name='Шкала баллов')),
                ('current_academic_year', models.CharField(blank=True, default='2025-2026', max_length=20, verbose_name='Текущий учебный год')),
                ('logo', models.ImageField(blank=True, help_text='Для шапки PDF-документов', null=True, upload_to='settings/', verbose_name='Логотип школы')),
                ('default_variants_count', models.IntegerField(default=2, help_text='При генерации работы', verbose_name='Кол-во вариантов по умолчанию')),
                ('pdf_font_size', models.IntegerField(default=12, help_text='pt', verbose_name='Размер шрифта PDF')),
                ('pdf_margin_top', models.IntegerField(default=15, help_text='мм', verbose_name='Отступ сверху PDF')),
                ('pdf_margin_bottom', models.IntegerField(default=15, help_text='мм', verbose_name='Отступ снизу PDF')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
