# Generated by Django 5.2.3 on 2026-08-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='current_academic_year',
        ),
    ]
