# Generated by Django 5.2.3 on 2026-07-19 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('template_type', models.CharField(choices=[('work', 'Контрольная / самостоятельная'), ('remedial_sheet', 'Работа над ошибками'), ('worksheet', 'Рабочий лист'), ('answer_key', 'Ключ для проверки'), ('homework', 'Домашнее задание'), ('diagnostic', 'Диагностическая карта'), ('custom', 'Пользовательский')], max_length=50, verbose_name='Тип шаблона')),
                ('sections_config', models.JSONField(blank=True, default=list, help_text='JSON: [{"type": "header", "params": {...}}, ...]', verbose_name='Конфигурация секций')),
                ('default_content_config', models.JSONField(blank=True, default=dict, verbose_name='Параметры контента по умолчанию')),
                ('latex_template_override', models.TextField(blank=True, verbose_name='Переопределение LaTeX-шаблона')),
                ('html_template_override', models.TextField(blank=True, verbose_name='Переопределение HTML-шаблона')),
                ('custom_css', models.TextField(blank=True, verbose_name='Пользовательский CSS')),
                ('custom_latex_preamble', models.TextField(blank=True, verbose_name='Пользовательская LaTeX-преамбула')),
                ('is_default', models.BooleanField(default=False, verbose_name='Шаблон по умолчанию')),
                ('is_public', models.BooleanField(default=False, verbose_name='Доступен всем учителям')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['-is_default', 'template_type', 'name'],
            },
        ),
    ]
