# Generated by Django 5.2.3 on 2026-07-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0003_rename_document_template_to_print_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printsettings',
            options={'ordering': ['-is_default', 'document_type', 'name'], 'verbose_name': 'Профиль оформления', 'verbose_name_plural': 'Профили оформления'},
        ),
        migrations.RemoveField(
            model_name='printsettings',
            name='default_content_config',
        ),
    ]
