# Generated by Django 5.2.3 on 2026-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0006_remove_printsettings_sections_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsettings',
            name='document_type',
            field=models.CharField(choices=[('work', 'Контрольная / самостоятельная'), ('remedial_sheet', 'Работа над ошибками'), ('event_performance_report', 'Отчёт по результатам работы'), ('student_digest', 'Дайджест оценок'), ('worksheet', 'Рабочий лист'), ('answer_key', 'Ключ для проверки'), ('homework', 'Домашнее задание'), ('diagnostic', 'Диагностическая карта'), ('custom', 'Пользовательский')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
